name: 🚀 release

on:
  release:
    types: [published]

permissions: {}

jobs:
  release:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish create-harmonix
        working-directory: packages/create-harmonix
        run: pnpm publish --access public --no-git-checks --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Publish harmonix-cli
        working-directory: packages/harmonix-cli
        run: pnpm publish --access public --no-git-checks --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
