name: 🚀 release

on:
  push:
    branches:
      - main

jobs:
  release:
    strategy:
      matrix:
        version:
          - major
          - minor
          - patch

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - run: corepack enable
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm prepack

      - name: Update version
        run: |
          case ${{ matrix.version }} in
            patch)
              npm version patch ;;
            minor)
              npm version minor ;;
            major)
              npm version major ;;
            *)
              echo "Invalid version provided"; exit 1 ;;
          esac

      # - name: Release
      #   run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
